// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFr1o8r5kmgQZjqE6nDyQJs_rziK0fmeo',
    appId: '1:513887305534:web:6509551b5ba7994d52b66f',
    messagingSenderId: '513887305534',
    projectId: 'safify-itsm',
    authDomain: 'safify-itsm.firebaseapp.com',
    storageBucket: 'safify-itsm.appspot.com',
    measurementId: 'G-78MM2YCXNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO2pP08Bg_ZBxdn2Br5sLLbTMmyXz1uSo',
    appId: '1:513887305534:android:a6f1984bdab6060552b66f',
    messagingSenderId: '513887305534',
    projectId: 'safify-itsm',
    storageBucket: 'safify-itsm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWJ8d-dls6pImGElGBrwtFA3tjXSEchwI',
    appId: '1:513887305534:ios:1509da40e21eba9752b66f',
    messagingSenderId: '513887305534',
    projectId: 'safify-itsm',
    storageBucket: 'safify-itsm.appspot.com',
    iosBundleId: 'com.safify.itsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWJ8d-dls6pImGElGBrwtFA3tjXSEchwI',
    appId: '1:513887305534:ios:1509da40e21eba9752b66f',
    messagingSenderId: '513887305534',
    projectId: 'safify-itsm',
    storageBucket: 'safify-itsm.appspot.com',
    iosBundleId: 'com.safify.itsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFr1o8r5kmgQZjqE6nDyQJs_rziK0fmeo',
    appId: '1:513887305534:web:e223e4d83982138d52b66f',
    messagingSenderId: '513887305534',
    projectId: 'safify-itsm',
    authDomain: 'safify-itsm.firebaseapp.com',
    storageBucket: 'safify-itsm.appspot.com',
    measurementId: 'G-RD5B9TBRWB',
  );
}
